version: 2
updates:
  # Swift Package Manager dependencies
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "tiaastor"
    labels:
      - "dependencies"
      - "swift"
    # Auto-merge minor and patch updates for dev dependencies
    # Note: This requires GitHub Pro/Team for security reasons
