# AFL Fantasy Platform - Docker Compose
# This extends the unified configuration with production-ready settings

include:
  - docker-compose.unified.yml

services:
  # Production overrides for backend service
  backend:
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    profiles: ["default", "production"]

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    profiles: ["production", "proxy"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - afl-network
    restart: unless-stopped
