name: AFL Fantasy
options:
  bundleIdPrefix: com.tiaastor
  deploymentTarget: 
    iOS: 17.0
  xcodeVersion: "15.0"

targets:
  AFL Fantasy:
    type: application
    platform: iOS
    sources: 
      - path: AFL Fantasy
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
        DEVELOPMENT_TEAM: ""
        PRODUCT_NAME: "AFL Fantasy"
        PRODUCT_BUNDLE_IDENTIFIER: "com.tiaastor.AFLFantasy"
