name: AFLFantasy
options:
  bundleIdPrefix: com.tiaastor
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  defaultConfig: Debug

configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig

configs:
  Debug: debug
  Release: release

fileGroups:
  - Sources
  - Resources
  - Tests
  - Scripts

targets:
  AFL Fantasy Free:
    type: application
    platform: iOS
    sources:
      - path: Sources/Shared
        excludes:
          - AFLFantasyApp.swift
      - path: Sources/Free
    resources:
      - Resources/Assets.xcassets
    info:
      path: Configs/AFLFantasyFree-Info.plist
      properties:
        CFBundleDisplayName: AFL Fantasy
        CFBundleName: AFL Fantasy
        CFBundleIdentifier: com.tiaastor.AFLFantasy
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
    settings:
      base:
        PRODUCT_NAME: AFL Fantasy
        PRODUCT_BUNDLE_IDENTIFIER: com.tiaastor.AFLFantasy
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_TREAT_WARNINGS_AS_ERRORS: true
        ENABLE_STRICT_OBJC_MSGSEND: true
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_IDENTITY: "iPhone Developer"
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SWIFT_COMPILATION_MODE: wholemodule

  AFL Fantasy Pro:
    type: application 
    platform: iOS
    sources:
      - path: Sources/Shared
        excludes:
          - AFLFantasyApp.swift
      - path: Sources/Pro
    resources:
      - Resources/Assets.xcassets
    info:
      path: Configs/AFLFantasyPro-Info.plist
      properties:
        CFBundleDisplayName: AFL Fantasy Pro
        CFBundleName: AFL Fantasy Pro
        CFBundleIdentifier: com.tiaastor.AFLFantasyPro
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
    settings:
      base:
        PRODUCT_NAME: AFL Fantasy Pro
        PRODUCT_BUNDLE_IDENTIFIER: com.tiaastor.AFLFantasyPro
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_TREAT_WARNINGS_AS_ERRORS: true
        ENABLE_STRICT_OBJC_MSGSEND: true
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_IDENTITY: "iPhone Developer"
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG PRO_VERSION
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SWIFT_COMPILATION_MODE: wholemodule

  AFL Fantasy Pro Widget:
    type: app-extension
    platform: iOS
    sources:
      - path: Widget
    info:
      path: Widget/Info.plist
    settings:
      base:
        PRODUCT_NAME: AFL Fantasy Pro Widget
        PRODUCT_BUNDLE_IDENTIFIER: com.tiaastor.AFLFantasyPro.Widget
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: AFL Fantasy Pro
        embed: true

  AFLFantasyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
    dependencies:
      - target: AFL Fantasy Free
      - target: AFL Fantasy Pro
    settings:
      base:
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  AFL Fantasy Free:
    build:
      targets:
        AFL Fantasy Free: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AFLFantasyTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  AFL Fantasy Pro:
    build:
      targets:
        AFL Fantasy Pro: all
        AFL Fantasy Pro Widget: all
    run:
      config: Debug
    test:
      config: Debug 
      targets:
        - AFLFantasyTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
