apiVersion: v1
kind: ConfigMap
metadata:
  name: afl-fantasy-config
  namespace: afl-fantasy
data:
  NODE_ENV: "production"
  PORT: "5000"
  CHROME_BIN: "/usr/bin/chromium-browser"
  CHROME_PATH: "/usr/lib/chromium/"
  LOG_LEVEL: "info"
  API_RATE_LIMIT: "1000"
  SESSION_TIMEOUT: "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: afl-fantasy
data:
  nginx.conf: |
    upstream afl_fantasy_backend {
        least_conn;
        server afl-fantasy-app:5000 max_fails=3 fail_timeout=30s;
    }
    
    server {
        listen 80;
        server_name _;
        
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
        
        location / {
            proxy_pass http://afl_fantasy_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }