apiVersion: v1
kind: Secret
metadata:
  name: afl-fantasy-secrets
  namespace: afl-fantasy
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/afl_fantasy"
  POSTGRES_PASSWORD: "password"
  
  # Redis connection
  REDIS_URL: "redis://redis-service:6379"
  
  # API Keys (replace with actual values)
  AFL_FANTASY_USERNAME: ""
  AFL_FANTASY_PASSWORD: ""
  DFS_AUSTRALIA_API_KEY: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  
  # Session security
  SESSION_SECRET: "your-super-secret-session-key-change-this"
  JWT_SECRET: "your-jwt-secret-key-change-this"