name: Node.js CI
on:
  push:
    branches: [main, develop]
    paths:
      - 'server-node/**'
      - 'package*.json'
      - '.github/workflows/node.yml'
  pull_request:
    branches: [main]
    paths:
      - 'server-node/**'
      - 'package*.json'

jobs:
  test:
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint:check
      
      - name: Type check
        run: npm run check
      
      - name: Format check
        run: npm run format:check
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Build
        run: npm run build
      
      - name: Check bundle size
        run: |
          if [ -f scripts/size-gate.sh ]; then
            bash scripts/size-gate.sh
          fi
      
      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Test API endpoints
        run: |
          # Start server in background
          npm run start &
          SERVER_PID=$!
          sleep 5
          
          # Test health endpoint
          curl -f http://localhost:5000/api/health || exit 1
          
          # Kill server
          kill $SERVER_PID
        continue-on-error: true
