# AFL Fantasy Intelligence iOS App - SwiftLint Configuration
# Enterprise-grade linting rules following HIG guidelines

disabled_rules:
  - trailing_comma
  - file_header

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_name
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - modifier_order
  - redundant_nil_coalescing
  - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - yoda_condition
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - attributes
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher

included: 
  - Sources
  - Tests

excluded: 
  - Generated
  - .build
  - Scripts
  - Resources

analyzer_rules: 
  - unused_import
  - unused_declaration

# Size & complexity limits
line_length: 
  warning: 120
  error: 140

file_length: 
  warning: 400
  error: 500

type_body_length: 
  warning: 300
  error: 400

function_body_length: 
  warning: 40
  error: 60

cyclomatic_complexity: 
  warning: 10
  error: 12

nesting: 
  type_level: 2
  statement_level: 3

# Safety rules
force_cast: error
force_try: error
force_unwrapping: error

# Naming conventions
identifier_name:
  min_length: 2
  max_length: 40
  excluded: [id, x, y, to, up, on]

type_name:
  min_length: 3
  max_length: 40

# Whitespace rules
trailing_whitespace: error
vertical_whitespace: 
  max_empty_lines: 1

# Documentation
missing_docs:
  warning:
    - public
    - open
  excludes_extensions: true
  excludes_inherited_types: true

# Custom rules for AFL Fantasy Intelligence
custom_rules:
  force_unwrapping_in_tests:
    name: "Force Unwrapping in Tests"
    regex: '(try!|!)(?=.*Test)'
    match_kinds:
      - keyword
    severity: warning
    message: "Prefer safe unwrapping in tests using XCTUnwrap"
  
  todo_without_jira:
    name: "TODO without ticket"
    regex: 'TODO(?!.*AFL-\d+)'
    severity: warning
    message: "TODOs should reference a ticket number (e.g., TODO: AFL-123)"

# Reporting
reporter: "xcode"

disabled_rules:
  - trailing_comma
  - file_header
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_name
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - modifier_order
  - redundant_nil_coalescing
  - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - yoda_condition
included: [Sources, Tests]
excluded: [Generated, .build, Scripts]
analyzer_rules: [unused_import, unused_declaration]

# Size & complexity
line_length: { warning: 120, error: 140 }
file_length: { warning: 400, error: 500 }
type_body_length: { warning: 300, error: 400 }
function_body_length: { warning: 40, error: 60 }
cyclomatic_complexity: { warning: 10, error: 12 }
nesting: { type_level: 2 }

# Safety
force_cast: error
force_try: error
force_unwrapping: error

# Naming
identifier_name:
  min_length: 2
  max_length: 40
  excluded: [id, x, y, to, up]

trailing_whitespace: error
vertical_whitespace: { max_empty_lines: 1 }

reporter: "xcode"
