name: AFL Fantasy Intelligence
options:
  bundleIdPrefix: com.aflsi
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  
settings:
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  AFL Fantasy Intelligence:
    type: application
    platform: iOS
    sources:
      - path: Sources
        headerVisibility: public
    resources:
      - Resources/**
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: "AFL Fantasy Intelligence"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "APPL"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSExceptionMinimumTLSVersion: "1.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aflsi.fantasy-intelligence
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      SWIFT_TREAT_WARNINGS_AS_ERRORS: true
      SWIFT_STRICT_CONCURRENCY: complete
      DEAD_CODE_STRIPPING: true
      ENABLE_TESTABILITY: false
      ONLY_ACTIVE_ARCH: false
      STRIP_INSTALLED_PRODUCT: true
    dependencies: []

  AFL Fantasy Intelligence Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/Unit
    dependencies:
      - target: AFL Fantasy Intelligence
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AFL Fantasy Intelligence.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/AFL Fantasy Intelligence"
      BUNDLE_LOADER: "$(TEST_HOST)"

  AFL Fantasy Intelligence UI Tests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/UI
    dependencies:
      - target: AFL Fantasy Intelligence

packages:
  swift-collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.0"

schemes:
  AFL Fantasy Intelligence:
    build:
      targets:
        AFL Fantasy Intelligence: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AFL Fantasy Intelligence Tests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
